name: income_insight
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  riverpod: ^2.4.9
  lottie: ^3.0.0
  flutter_riverpod: ^2.4.9
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  glassmorphism_ui: ^0.3.0
  hexcolor: ^3.0.1
  cloud_firestore: ^4.14.0
  curved_navigation_bar: ^1.0.3
  form_validator: ^2.1.1
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  http: ^1.2.0
  flutter_echart: ^2.0.0
  image_picker: ^1.0.7
  pull_to_refresh: ^2.0.0
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^5.0.2
  package_info_plus: ^5.0.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1

flutter:


  uses-material-design: true


  assets:
    - animation/
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
